DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 448
  TEST:
    BATCH_SIZE: 500

OPTIM:
  NAME: "sgd"
  LR: 0.05
  STEPSIZE: [4000]
  MAX_EPOCH: 4000
  LR_SCHEDULER: "cosine"

TRAIN:
  COUNT_ITER: "train_u"
  PRINT_FREQ: 10

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ["random_flip", "randaugment_fixmatch", "normalize", "cutout"]