INPUT:
  PIXEL_MEAN: [0., 0., 0.]
  PIXEL_STD: [1., 1., 1.]

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128

OPTIM:
  NAME: "sgd"
  LR: 0.05
  STEPSIZE: [20]
  MAX_EPOCH: 50

TRAINER:
  DDAIG:
    G_ARCH: "fcn_3x32_gctx"
    LMDA: 0.3